Try to catch Throwable rather than Exception since NoSuchMethodError is a throwable (https://stackoverflow.com/questions/38283476/java-nosuchmethoderror-not-caught-by-exception)